$include:
  - conf/final/16khz.yml

# Override rates to match 6.25 Hz
# default rates are [2, 4, 5, 8] for encoder and [8, 5, 4, 2] for decoder, which correspond to a total downsampling factor of 320 (16000 / 320 = 50 Hz)
# To achieve 6.25 Hz, we need a total downsampling factor of 2560 (16000 / 2560 = 6.25 Hz)
DAC.encoder_rates: [4, 8, 8, 10]
DAC.decoder_rates: [10, 8, 8, 4]

MelSpectrogramLoss.n_mels:         [5, 10, 20, 40, 80, 160, 320, 640]
MelSpectrogramLoss.window_lengths: [32, 64, 128, 256, 512, 1024, 2048, 4096]
MelSpectrogramLoss.mel_fmin:       [0, 0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLoss.mel_fmax:       [null, null, null, null, null, null, null, null]

num_iters: 100000
save_iters: [10000, 50000, 100000]
valid_freq: 10000

train/AudioDataset.duration: 0.4

# Override data paths
train/build_dataset.folders:
  speech:
    - ./data/librispeech/train-clean-100

val/build_dataset.folders:
  speech:
    - ./data/librispeech/dev-clean

test/build_dataset.folders:
  speech:
    - ./data/librispeech/test-clean

# Adjust batch size based on your GPU memory
batch_size: 32
val_batch_size: 32
num_workers: 4